# Generated by Django 5.2.3 on 2025-09-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_url_event_is_almost_full_event_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_almost_full',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_free',
        ),
    ]
