# Generated by Django 5.2.6 on 2025-09-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_city_event_owner_alter_event_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
