# Generated by Django 5.2.6 on 2025-09-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
