# Generated by Django 5.2.6 on 2025-09-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_options_event_created_at_event_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='created_at',
        ),
    ]
